name: Deploy Quartz site to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - quartz

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      # - name: Checkout external repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: HugManh/brain-IT
      #     ref: development
      #     path: content
      #     token: ${{ secrets.SECRET_KEY }}
      - name: Checkout external repository
        run: |
          git clone --no-checkout https://${{ secrets.SECRET_KEY }}@github.com/HugManh/brain-IT.git external-repo
          cd external-repo
          git sparse-checkout init --cone
          git sparse-checkout set Categories Attachments # Chỉ định hai thư mục cần lấy
          git checkout development # Thay 'main' bằng nhánh của repo cần clone
      - name: Copy content to folder
        run: |
          rm -rf content/*
          cp -r external-repo/Categories/* content/
          cp -r external-repo/Attachments content/
          rm -rf external-repo
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Post blocks to a Slack channel
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "🚀 Deploy thành công lên GitHub Pages!\n🔗 URL: ${{ steps.deployment.outputs.page_url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "🚀 Deploy thành công lên GitHub Pages!\n🔗 URL: ${{ steps.deployment.outputs.page_url }}"
