name: Tasks Workflow

on:
  schedule:
    - cron: "*/1 * * * *" # chạy mỗi 1 phút
    # - cron: "0 23 * * *" # mỗi ngày 23:00 chạy 1 lần
  push:
    branches:
      - quartz

run-name: ${{ github.actor }} Schedule Tasks 🚀

jobs:
  trigger-deplop-website:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Quartz site to GitHub Pages
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SECRET_KEY }}
          repository: HugManh/docs-app
          event-type: Integration-with-Automation-Deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Hello
        run: "echo ${{ github.actor }} Hello !"
